using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DataAccessLayer.Seeds
{
    public class BiletSeed
    {
        public static List<Bilet> GetSeeds()
        {
            return new List<Bilet>
            {
                new Bilet
                {
                    Tarih = new DateOnly(2024, 9, 30),
                    TurId = 2,
                    AracId = null,
                    ServisId = null,
                    SatanSubeId = 1,
                    SatanElemanId = 3,
                    MusteriAd = "Ali",
                    MusteriSoyad = "Kaya",
                    MusteriUyruk = "TUR",
                    MusteriBolgeId = 1,
                    MusteriOtelId = null,
                    MusteriOdaNo = null,
                    MusteriAdres = "Antalya Merkez",
                    MusteriTelNo = "+905125481483",
                    FullSayi = 1,
                    HalfSayi = 1,
                    GuestSayi = 0,
                    ParaBirimi = "TRY",
                    Paid = 70,
                    Rest = 80,
                    OdendiMi = false,
                    Aciklama = null,
                    ServisIstiyorMu = false,
                    ServisSaati = null,
                    BiletIptalMi = true,
                    PasBiletMi = false,
                    GelenGidenPas = null,
                    PasSirketi = null
                },
                new Bilet
                {
                    Tarih = new DateOnly(2024, 9, 30),
                    TurId = 2,
                    AracId = 1,
                    ServisId = null,
                    SatanSubeId = 2,
                    SatanElemanId = 7,
                    MusteriAd = "Veli",
                    MusteriSoyad = "Türkoğlu",
                    MusteriUyruk = "TUR",
                    MusteriBolgeId = 2,
                    MusteriOtelId = null,
                    MusteriOdaNo = null,
                    MusteriAdres = "Antalya Bölge 1",
                    MusteriTelNo = "+905125481483",
                    FullSayi = 1,
                    HalfSayi = 0,
                    GuestSayi = 0,
                    ParaBirimi = "TRY",
                    Paid = 50,
                    Rest = 50,
                    OdendiMi = true,
                    Aciklama = null,
                    ServisIstiyorMu = false,
                    ServisSaati = null,
                    BiletIptalMi = false,
                    PasBiletMi = false,
                    GelenGidenPas = null,
                    PasSirketi = null
                },
                new Bilet
                {
                    Tarih = new DateOnly(2024, 10, 2),
                    TurId = 4,
                    AracId = 1,
                    ServisId = null,
                    SatanSubeId = 1,
                    SatanElemanId = 3,
                    MusteriAd = "Mehmet",
                    MusteriSoyad = "Yılmaz",
                    MusteriUyruk = "TUR",
                    MusteriBolgeId = 1,
                    MusteriOtelId = null,
                    MusteriOdaNo = null,
                    MusteriAdres = "Antalya Merkez",
                    MusteriTelNo = "+905321234567",
                    FullSayi = 2,
                    HalfSayi = 1,
                    GuestSayi = 0,
                    ParaBirimi = "TRY",
                    Paid = 150,
                    Rest = 150,
                    OdendiMi = false,
                    Aciklama = "Yol tutuyor.",
                    ServisIstiyorMu = false,
                    ServisSaati = null,
                    BiletIptalMi = false,
                    PasBiletMi = false,
                    GelenGidenPas = null,
                    PasSirketi = null
                },
                new Bilet
                {
                    Tarih = new DateOnly(2024, 10, 2),
                    TurId = 4,
                    AracId = 2,
                    ServisId = null,
                    SatanSubeId = 1,
                    SatanElemanId = 3,
                    MusteriAd = "John",
                    MusteriSoyad = "Doe",
                    MusteriUyruk = "USA",
                    MusteriBolgeId = 1,
                    MusteriOtelId = 1,
                    MusteriOdaNo = "101",
                    MusteriAdres = null,
                    MusteriTelNo = "+905256247314",
                    FullSayi = 1,
                    HalfSayi = 0,
                    GuestSayi = 0,
                    ParaBirimi = "USD",
                    Paid = 4,
                    Rest = 6,
                    OdendiMi = false,
                    Aciklama = null,
                    ServisIstiyorMu = true,
                    ServisSaati = new TimeOnly(9, 30),
                    BiletIptalMi = false,
                    PasBiletMi = false,
                    GelenGidenPas = null,
                    PasSirketi = null
                },
                new Bilet
                {
                    Tarih = new DateOnly(2024, 10, 3),
                    TurId = 4,
                    AracId = null,
                    ServisId = null,
                    SatanSubeId = 1,
                    SatanElemanId = 3,
                    MusteriAd = "Jack",
                    MusteriSoyad = "American",
                    MusteriUyruk = "USA",
                    MusteriBolgeId = 1,
                    MusteriOtelId = 2,
                    MusteriOdaNo = "102",
                    MusteriAdres = null,
                    MusteriTelNo = "+905842924039",
                    FullSayi = 2,
                    HalfSayi = 1,
                    GuestSayi = 0,
                    ParaBirimi = "USD",
                    Paid = 12,
                    Rest = 13,
                    OdendiMi = false,
                    Aciklama = null,
                    ServisIstiyorMu = true,
                    ServisSaati = new TimeOnly(9, 30),
                    BiletIptalMi = false,
                    PasBiletMi = false,
                    GelenGidenPas = null,
                    PasSirketi = null
                },
                new Bilet
                {
                    Tarih = new DateOnly(2024, 10, 3),
                    TurId = 5,
                    AracId = null,
                    ServisId = null,
                    SatanSubeId = 2,
                    SatanElemanId = 7,
                    MusteriAd = "Klaus",
                    MusteriSoyad = "Müller",
                    MusteriUyruk = "DEU",
                    MusteriBolgeId = 2,
                    MusteriOtelId = 3,
                    MusteriOdaNo = "206",
                    MusteriAdres = null,
                    MusteriTelNo = "+905923517421",
                    FullSayi = 1,
                    HalfSayi = 3,
                    GuestSayi = 0,
                    ParaBirimi = "EUR",
                    Paid = 20,
                    Rest = 20,
                    OdendiMi = false,
                    Aciklama = null,
                    ServisIstiyorMu = true,
                    ServisSaati = new TimeOnly(10,00),
                    BiletIptalMi = false,
                    PasBiletMi = false,
                    GelenGidenPas = null,
                    PasSirketi = null
                }
            };
        }
    }
}
